services:
  - type: web
    name: freelancer-tracker-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://varshitasharma11_db_user:NNP2zdGAAExuojYV@noteshubcluster.nym9l32.mongodb.net/freelancer_tracker?retryWrites=true&w=majority&appName=NotesHubCluster
      - key: JWT_SECRET
        value: 9b2d8f63a4e7c1d5f9b4c2e8a6d3f1b7e4c5a9d2b8f3e7c1a5d9b6f4e2c8a1d7
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
